import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";


export const metadata: Metadata = {
  title: "CodeLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`bg-dark-10 initialised`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
