import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "CodeLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`antialiased`}
      >
        <h1>Public Route</h1>
        {children}
      </body>
    </html>
  );
}
